language: erlang
otp_release:
  - 17.0
before_install:
  - git clone https://github.com/elixir-lang/elixir
  - cd elixir && git checkout v0.15.1 && make && cd ..
before_script:
  - export PATH=`pwd`/elixir/bin:$PATH
  - mix local.hex --force
  - mix deps.get
script:
  - MIX_ENV=all mix test
